#pragma once

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080

#define TILE_COUNT 19

#define TILE_WIDTH 192
#define TILE_HEIGHT 192

#define TILEMAP_WIDTH 100
#define TILEMAP_HEIGHT 20

#define MAP_WIDTH TILEMAP_WIDTH * TILE_WIDTH
#define MAP_HEIGHT TILEMAP_HEIGHT * TILE_HEIGHT

#define CAMERA_ZOOM_FACTOR 0.5